import { Alert } from '@/shared/components/Alert'
import { StoreProvider } from '@/shared/store/providers'
import { Header } from '@/widgets/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NoAgeNotAllowed } from '@/entities/auth'
import { ToastContainer } from '@/features/notifications'

const inter = Inter({
   variable: '--font-inter',
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
   icons: {
      icon: [
         {
            media: '(prefers-color-scheme: light)',
            url: '/logo-dark.svg',
            href: '/logo-dark.svg',
         },
         {
            media: '(prefers-color-scheme: dark)',
            url: '/logo-light.svg',
            href: '/logo-light.svg',
         },
      ],
      apple: [
         {
            media: '(prefers-color-scheme: light)',
            url: '/logo-dark.png',
            href: '/logo-dark.png',
         },
         {
            media: '(prefers-color-scheme: dark)',
            url: '/logo-light.png',
            href: '/logo-light.png',
         },
      ],
   },
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <StoreProvider>
         <html lang="en">
            <body className={`${inter.variable} min-h-screen`}>
               <Header notificationCount={4} />
               {children}
               <Alert />
               <NoAgeNotAllowed />
               <ToastContainer />
            </body>
         </html>
      </StoreProvider>
   )
}
