import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
   variable: '--font-inter',
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
   icons: {
      icon: [
         {
            url: '/logo-dark.svg',
            href: '/logo-dark.svg',
         },
         {
            media: '(prefers-color-scheme: light)',
            url: '/logo-dark.svg',
            href: '/logo-dark.svg',
         },
         {
            media: '(prefers-color-scheme: dark)',
            url: '/logo-light.svg',
            href: '/logo-light.svg',
         },
      ],
   },
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={`${inter.variable}`}>{children}</body>
      </html>
   )
}
